### ISSUE TITLE
Hey, I'm not very familiar with docker and docker-compose, could you help me with something?

### ISSUE THREAD

**Issue by Evertt** [matusstas/openai-whisper-microservice#1]
I'm trying to add your image to my `docker-compose.yml` file, which I think managed to do mostly successfully. This is what my `docker-compose.yml` file looks like right now:

```yml
version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PORT: ${PORT}
    container_name: deno-telegram-bot
    image: deno-telegram-bot-image
    ports:
      - "${PORT}:${PORT}"
    networks:
      - telegrambot
    depends_on:
      - whisper
  whisper:
    image: "matusstas/openai-whisper-microservice:latest"
    container_name: whisper-microservice
    ports:
      - 81:80
    networks:
      - telegrambot
    volumes:
      - models:/root/.cache/whisper
      - db:/app/db

networks:
  telegrambot:
    driver: bridge

volumes:
  models:
    driver: local
  db:
    driver: local
```

When I run `docker compose -f docker-compose.yml up --build`, I indeed get a container from your image. However, of course no models have been downloaded yet, and I was wondering if I could add a command to download the `base.en` model as one of the build steps.

I tried running `command: "curl --request POST http://localhost:81/model?model_name=base.en"`, but that didn't seem to work.
Can you tell me how I might accomplish that?

### Edit

Also, to be completely honest, I have no idea what `networks` and `volumes` in my `docker-compose.yml` file do, or how they can be used. I just put them there, because I was looking at another `docker-compose.yml` file that used multiple services as an example.

### Edit 2

Okay, so I just made it work by making a fetch request from my `web` service to my `whisper` service to download the model.

But now I'm running into a new problem. Even when I use the model `tiny.en`, the transcription seems to take ages. Like literally I've been waiting for minutes now and I haven't received any response yet (also no error responses).

Is it really that resource intense to run this microservice?

Oh, I just got an internal server error back from the whisper micro-service on my transcript request...
